// One-off: generates a REAL week-1 plan for Priya through the real pipeline
// (aiClinicalReview -> generateDietPlan [overview + all day batches, with
// exchangeBlock() wired in] -> groundPlan()), then saves it as a normal
// draft diet_plans row under the given dietitian so it shows up in the UI
// exactly like a plan generated by clicking the button — just run from a
// script instead of a browser, so the meals can be inspected here first.
//
// Skips the /api/plan-step stage machine (no fix:N reconciliation rounds) and
// the "pause" gate on the clinical review — this is a manual QA run, not the
// production endpoint. Run: npx tsx scripts/generate-priya-plan.mts <dietitian-email>
import { createClient } from "@supabase/supabase-js";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
function loadEnvLocal() {
  const text = readFileSync(join(root, ".env.local"), "utf8");
  for (const line of text.split(/\r?\n/)) {
    const m = line.match(/^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)\s*$/);
    if (m && !(m[1] in process.env)) process.env[m[1]] = m[2];
  }
}
loadEnvLocal();

const email = process.argv[2];
if (!email) {
  console.error("Usage: npx tsx scripts/generate-priya-plan.mts <dietitian-email>");
  process.exit(1);
}

const supabase = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.SUPABASE_SERVICE_ROLE_KEY!, {
  auth: { persistSession: false, autoRefreshToken: false },
});

const { toIntake } = await import("../src/lib/counselling/assessment");
const { PRIYA } = await import("./test-clients");
const { aiClinicalReview, isPauseDecision, generateDietPlan } = await import("../src/lib/nim");
const { groundPlan } = await import("../src/lib/nutrition");

const toNum = (v: unknown) => {
  const n = Number(v);
  return Number.isFinite(n) ? n : null;
};

async function main() {
  const { data: profile, error: profileError } = await supabase
    .from("profiles")
    .select("id, email, full_name")
    .ilike("email", email)
    .maybeSingle();
  if (profileError || !profile) {
    console.error("Profile lookup failed:", profileError?.message ?? "not found");
    process.exit(1);
  }
  console.log(`Dietitian: ${profile.full_name || profile.email} (${profile.id})`);

  const intake = toIntake(PRIYA as any);

  console.log("\nRunning AI clinical review...");
  const review = await aiClinicalReview(intake);
  console.log(`Decision: ${review.decision}`);
  console.log(`Safety: ${review.safety_classification}`);
  if (isPauseDecision(review)) {
    console.log("Review returned a PAUSE decision — proceeding anyway (manual QA run):");
    console.log(review.missing_information);
  }

  const { data: client, error: clientError } = await supabase
    .from("clients")
    .insert({
      dietitian_id: profile.id,
      full_name: intake.fullName.trim(),
      age: toNum(intake.age),
      gender: intake.gender || null,
      height_cm: toNum(intake.heightCm),
      weight_kg: toNum(intake.weightKg),
      goal: intake.goal || null,
      diet_type: intake.dietType || null,
      phone: intake.phone || null,
      email: intake.email || null,
      intake,
    })
    .select("id")
    .single();
  if (clientError) {
    console.error("Client insert failed:", clientError.message);
    process.exit(1);
  }
  console.log(`\nCreated client: ${client.id}`);

  console.log("\nGenerating week 1 plan via NVIDIA NIM (overview + 4 day batches)...");
  const t0 = Date.now();
  const ctx = { intake, week: 1, review };
  let raw: any = null;
  for (let attempt = 1; attempt <= 4 && !raw; attempt++) {
    try {
      raw = await generateDietPlan(ctx as any);
    } catch (e) {
      console.log(`attempt ${attempt} failed (${e instanceof Error ? e.message.slice(0, 120) : e}), retrying...`);
    }
  }
  if (!raw) throw new Error("Generation failed after 4 attempts");
  console.log(`Generated in ${Math.round((Date.now() - t0) / 1000)}s`);

  console.log("\nGrounding against public.foods...");
  const { plan, stats } = await groundPlan(supabase as any, raw, intake.cuisines ? [intake.cuisines] : []);
  console.log("Grounding stats:", JSON.stringify(stats));

  const planStart = new Date();
  planStart.setDate(planStart.getDate() + 1);
  const startsOn = planStart.toISOString().slice(0, 10);

  const { data: planRow, error: planError } = await supabase
    .from("diet_plans")
    .insert({
      client_id: client.id,
      dietitian_id: profile.id,
      week_number: 1,
      source: "first_counselling",
      plan,
      status: "draft",
      starts_on: startsOn,
      revisions: [],
      generation: {},
      ai_review: review,
    })
    .select("id")
    .single();
  if (planError) {
    console.error("diet_plans insert failed:", planError.message);
    process.exit(1);
  }

  console.log(`\nSaved plan: ${planRow.id}`);
  console.log(`View it at: /clients/${client.id}`);

  console.log(`\n=== SUMMARY ===`);
  console.log(`${plan.summary}\n`);
  console.log(`Daily target: ${plan.daily_calories} kcal | P${plan.macros.protein_g} C${plan.macros.carbs_g} F${plan.macros.fat_g}`);

  for (const day of plan.days) {
    console.log(`\n--- ${day.day} (${day.total_calories} kcal) ---`);
    for (const meal of day.meals) {
      const items = meal.items.map((i: any) => `${i.food} (${i.quantity})`).join(", ");
      console.log(
        `  ${meal.name.padEnd(16)} ${meal.time.padEnd(6)} P${meal.protein_g} C${meal.carbs_g} F${meal.fat_g} ${meal.calories}kcal — ${items}`
      );
    }
  }

  console.log(`\n=== JSON (for programmatic inspection) ===`);
  console.log(JSON.stringify({ clientId: client.id, planId: planRow.id, plan }, null, 2));
}

main();
